name: 'Setup SSH Action'
description: 'Sets up SSH credentials inside the GitHub environment'
author: 'WayneChu'
branding:
  color: 'blue'
  icon: 'cloud'
inputs:
  ORIGIN:
    description: 'SSH origin'
    default: 'github.com'
    required: false
  SSHKEY:
    description: 'SSH key'
    required: true
  NAME:
    description: 'SSH host'
    required: false
  PORT:
    description: 'SSH port'
    required: false
  USER:
    description: 'SSH user'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
