name: macOS

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: ZzzTechCorp/github-ssh-action@v1.0.0
      with:
        SSHKEY: ${{ secrets.SSH_GITHUB }}
    - run: ssh -T git@github.com || true
    - uses: ZzzTechCorp/github-ssh-action@v1.0.0
      with:
        ORIGIN: ${{ secrets.HOST }}
        SSHKEY: ${{ secrets.SSH_KEY }}
        NAME: production
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
    - run: ssh production ls --help
